# Generated by Django 6.0.5 on 2026-05-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMURecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('ax_mg', models.IntegerField()),
                ('ay_mg', models.IntegerField()),
                ('az_mg', models.IntegerField()),
                ('gx_dps', models.IntegerField()),
                ('gy_dps', models.IntegerField()),
                ('gz_dps', models.IntegerField()),
                ('activity', models.CharField(max_length=20)),
            ],
        ),
    ]
